/*! \addtogroup Examples Examples 
 * This module contains many examples of usage. 
 * @{ 
 */
package edu.mit.csail.sdg.squander.examples.mock;

import edu.mit.csail.sdg.annotations.Ensures;
import edu.mit.csail.sdg.annotations.Modifies;
import edu.mit.csail.sdg.squander.Squander;

/**
 * Completely magic interface implementation. Ideally, should be autogenerated.
 * @author kuat
 *
 */
public class MockAddressBook implements AddressBook {
    
    public MockAddressBook() { init(); }
    
    @Ensures("no this.data")
    @Modifies("this.data")
    private void init() { Squander.exe(this); }
    
    @Override
    public void setEmailAddress(String name, String email) {
        Squander.exe(this, new Class<?>[]{String.class, String.class}, new Object[]{name, email});
    }

    @Override
    public String getEmailAddress(String name) {
        return Squander.exe(this, new Class<?>[]{String.class}, new Object[]{name});
    }

    @Override
    public boolean contains(String name) {
        return Squander.exe(this, new Class<?>[]{String.class}, new Object[]{name});
    }
}
/*! @} */
